import Link from"next/link";import{redirect}from"next/navigation";import{currentUser}from"@/lib/auth";import{projects,playableWebGames}from"@/lib/site-data";import{releases}from"@/lib/releases";import{projectMedia}from"@/lib/media";import{PageHeader}from"@/components/ui";
export const metadata={title:"Admin"};
export default async function Admin(){const user=await currentUser();if(!user)redirect("/login?next=/admin");if(user.role!=="OWNER"&&user.role!=="SYSTEM")redirect("/");
const webGames=playableWebGames();const published=releases.filter(r=>r.state==="published");
const stats=[["Projects",projects.length,"Static registry"],["Media",projectMedia.length,"Validated assets"],["Web Games",webGames.length,"Browser playable"],["Releases",published.length+"/"+releases.length,"Published / total"]];
return <><PageHeader eyebrow="CONTROL PLANE" title="Admin Console" description="Authorized operational view for projects, releases, web games and media."/>
<div className="warning"><b>Read-only safety mode</b><p>Signed in as {user.displayName} · {user.role}. Mutations remain locked until PostgreSQL migrations and end-to-end authorization tests pass.</p></div>
<div className="admin-stats">{stats.map(([label,value,note])=><div className="card admin-stat" key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>)}</div>
<section className="admin-section"><div className="section-title"><div><p className="eyebrow">REGISTRY</p><h2>Projects</h2></div><Link className="text-link" href="/projects">Public view →</Link></div><div className="admin-table"><div className="admin-row admin-head"><span>PROJECT</span><span>TYPE</span><span>STATUS</span><span>WEB PLAY</span></div>{projects.map(p=><div className="admin-row" key={p.slug}><Link href={"/projects/"+p.slug}>{p.name}</Link><span>{p.category}</span><span className="status">{p.status}</span><span>{p.runtime==="web"&&p.webGame?.enabled?"Enabled":"Disabled"}</span></div>)}</div></section>
<section className="admin-section"><div className="section-title"><div><p className="eyebrow">ARTIFACTS</p><h2>Release readiness</h2></div></div><div className="admin-table"><div className="admin-row admin-head"><span>PROJECT</span><span>VERSION</span><span>PLATFORM</span><span>STATE</span></div>{releases.map(r=><div className="admin-row" key={r.id}><span>{r.project}</span><code>{r.version}</code><span>{r.platform}</span><span className={"status "+(r.state==="published"?"ok":"")}>{r.state}</span></div>)}</div></section>
<div className="admin-checklist"><div className="card"><b>Mutation gate</b><ul><li>PostgreSQL container reachable</li><li>Prisma migration applied</li><li>OWNER bootstrap verified</li><li>Role authorization E2E passes</li><li>Audit log model enabled</li></ul></div><div className="card"><b>Media policy</b><ul><li>Images: validated local or object storage asset</li><li>Large video: object storage only</li><li>No placeholder download URLs</li><li>Web launcher: browser-native builds only</li></ul></div></div></>}
