"use client";
import { ContentKind } from "@prisma/client";
import { useState } from "react";
function obj(v:unknown){return typeof v==="object"&&v!==null&&!Array.isArray(v)?v as Record<string,unknown>:{}}
function lines(v:unknown){return Array.isArray(v)?v.join("\n"):""}
export function TypedFields({kind,data={},disabled=false}:{kind:string,data?:unknown,disabled?:boolean}){const d=obj(data);return <div className="typed-fields">
{kind==="PROJECT"&&<><label>Category<input name="category" defaultValue={String(d.category??"Software")} disabled={disabled}/></label><label>Status<input name="status" defaultValue={String(d.status??"Active")} disabled={disabled}/></label><label>Runtime<select name="runtime" defaultValue={String(d.runtime??"tool")} disabled={disabled}><option value="web">web</option><option value="desktop">desktop</option><option value="service">service</option><option value="tool">tool</option></select></label><label className="wide">Description<textarea name="description" defaultValue={String(d.description??"")} disabled={disabled}/></label><label className="wide">Summary<textarea name="summary" defaultValue={String(d.summary??"")} disabled={disabled}/></label><label>Tags (one per line)<textarea name="tags" defaultValue={Array.isArray(d.tags)?d.tags.map(x=>obj(x).name).filter(Boolean).join("\n"):""} disabled={disabled}/></label><label>Highlights (one per line)<textarea name="highlights" defaultValue={lines(d.highlights)} disabled={disabled}/></label></>}
{kind==="RELEASE"&&<><label>Project slug<input name="projectSlug" defaultValue={String(d.projectSlug??"")} disabled={disabled}/></label><label>Artifact<input name="artifact" defaultValue={String(d.artifact??"")} disabled={disabled}/></label><label>Version<input name="version" defaultValue={String(d.version??"")} disabled={disabled}/></label><label>Platform<input name="platform" defaultValue={String(d.platform??"Windows")} disabled={disabled}/></label><label>State<select name="state" defaultValue={String(d.state??"pending")} disabled={disabled}><option value="pending">pending</option><option value="published">published</option></select></label><label>HTTPS download URL<input name="downloadUrl" defaultValue={String(d.downloadUrl??"")} disabled={disabled}/></label><label className="wide">Changelog (one per line)<textarea name="changelog" defaultValue={lines(d.changelog)} disabled={disabled}/></label></>}
{kind==="MEDIA"&&<><label>Project slug<input name="projectSlug" defaultValue={String(d.projectSlug??"")} disabled={disabled}/></label><label>Kind<select name="mediaKind" defaultValue={String(d.kind??"image")} disabled={disabled}><option value="image">image</option><option value="video">video</option></select></label><label>Source<input name="src" defaultValue={String(d.src??"/media/")} disabled={disabled}/></label><label>Alt text<input name="alt" defaultValue={String(d.alt??"")} disabled={disabled}/></label><label className="wide">Caption<input name="caption" defaultValue={String(d.caption??"")} disabled={disabled}/></label></>}
{kind==="WEB_GAME"&&<><label>Project slug<input name="projectSlug" defaultValue={String(d.projectSlug??"")} disabled={disabled}/></label><label>Entry path / HTTPS URL<input name="entry" defaultValue={String(d.entry??"/games-content/")} disabled={disabled}/></label><label className="check"><input type="checkbox" name="enabled" defaultChecked={d.enabled===true} disabled={disabled}/> Enabled</label></>}
</div>}
export function CreateTypedFields(){const[kind,setKind]=useState<ContentKind>(ContentKind.PROJECT);return <><label>Kind<select name="kind" value={kind} onChange={e=>setKind(e.target.value as ContentKind)}>{Object.values(ContentKind).map(k=><option key={k}>{k}</option>)}</select></label><TypedFields kind={kind}/></>}
