import { ContentKind } from "@prisma/client";
import { db } from "@/lib/db";
import { mediaSchema, projectSchema, releaseSchema, webGameSchema } from "@/lib/content-validation";
import { projects, type Project } from "@/lib/site-data";
import { releases, type Release } from "@/lib/releases";
import { projectMedia, type ProjectMedia } from "@/lib/media";
function projectFrom(key:string,title:string,data:unknown):Project|null{const r=projectSchema.safeParse(data);if(!r.success)return null;const d=r.data,base=projects.find(p=>p.slug===key);return{slug:key,name:title,category:d.category,description:d.description,summary:d.summary,status:d.status,featured:base?.featured??false,runtime:d.runtime,tags:d.tags,highlights:d.highlights,repository:base?.repository,release:base?.release}}
function releaseFrom(key:string,title:string,data:unknown):Release|null{const r=releaseSchema.safeParse(data);if(!r.success)return null;const d=r.data;return{id:key,projectSlug:d.projectSlug,project:title,artifact:d.artifact,version:d.version,platform:d.platform,state:d.state,downloadUrl:d.downloadUrl,size:d.size,sha256:d.sha256,publishedAt:d.publishedAt,changelog:d.changelog}}
function mediaFrom(key:string,title:string,data:unknown):ProjectMedia|null{const r=mediaSchema.safeParse(data);if(!r.success)return null;const d=r.data;return{id:key,projectSlug:d.projectSlug,kind:d.kind,title,caption:d.caption,src:d.src,poster:d.poster,alt:d.alt}}
export async function publicProjects(){let rows;try{rows=await db.contentEntry.findMany({where:{kind:ContentKind.PROJECT,published:true,archivedAt:null}})}catch{return projects}if(!rows.length)return projects;const valid=new Map(rows.map(r=>[r.key,projectFrom(r.key,r.title,r.data)]));const merged=projects.map(p=>valid.get(p.slug)??p),known=new Set(projects.map(p=>p.slug));return[...merged,...rows.filter(r=>!known.has(r.key)).map(r=>projectFrom(r.key,r.title,r.data)).filter((p):p is Project=>Boolean(p))]}
export async function publicProject(slug:string){return(await publicProjects()).find(p=>p.slug===slug)}
export async function publicReleases(){let rows;try{rows=await db.contentEntry.findMany({where:{kind:ContentKind.RELEASE,published:true,archivedAt:null}})}catch{return releases}if(!rows.length)return releases;const parsed=rows.map(r=>releaseFrom(r.key,r.title,r.data)).filter((x):x is Release=>Boolean(x));return parsed.length?parsed:releases}
export async function publicMedia(slug:string){let rows;try{rows=await db.contentEntry.findMany({where:{kind:ContentKind.MEDIA,published:true,archivedAt:null}})}catch{return projectMedia.filter(x=>x.projectSlug===slug)}const parsed=rows.map(r=>mediaFrom(r.key,r.title,r.data)).filter((x):x is ProjectMedia=>Boolean(x)).filter(x=>x.projectSlug===slug);return parsed.length?parsed:projectMedia.filter(x=>x.projectSlug===slug)}
export async function playableWebGames(){let rows;const allProjects=await publicProjects();try{rows=await db.contentEntry.findMany({where:{kind:ContentKind.WEB_GAME,published:true,archivedAt:null}})}catch{return[]}const bySlug=new Map(allProjects.map(p=>[p.slug,p])),games:Project[]=[];for(const row of rows){const r=webGameSchema.safeParse(row.data);if(!r.success||!r.data.enabled)continue;const p=bySlug.get(r.data.projectSlug);if(!p||p.runtime!=="web")continue;games.push({...p,webGame:{enabled:true,entry:r.data.entry}})}return games}
export async function playableWebGame(slug:string){return(await playableWebGames()).find(p=>p.slug===slug)}
