export type Tag={name:string;kind:"language"|"tool"|"platform"};
export type Project={slug:string;name:string;category:string;description:string;status:string;tags:Tag[];featured?:boolean;summary:string;highlights:string[];runtime:"web"|"desktop"|"service"|"tool";repository?:string;release?:string;webGame?:{enabled:boolean;entry?:string}};
export const projects:Project[]=[
{slug:"project2080",name:"Project2080",category:"Game",description:"Extraction-style game project built as a production-focused vertical slice.",summary:"A Windows Unity project covering combat, inventory, progression, missions, bosses and release-candidate validation.",status:"Final Candidate",featured:true,runtime:"desktop",tags:[{name:"C#",kind:"language"},{name:"Unity",kind:"tool"},{name:"Windows",kind:"platform"}],highlights:["Windows desktop game","Release-candidate validation","Combat, loot and progression systems"]},
{slug:"remote-home",name:"REMOTE_HOME",category:"Server / Infra",description:"Remote development and home-computing environment for secure access and automation.",summary:"A remote development stack connecting the home workstation and mobile development workflow.",status:"Active",featured:true,runtime:"service",tags:[{name:"PowerShell",kind:"language"},{name:"OpenSSH",kind:"tool"},{name:"Tailscale",kind:"tool"}],highlights:["Remote SSH workflow","Private network access","Recovery-oriented automation"]},
{slug:"vbox-share-sync",name:"VirtualBox Share Sync",category:"Software",description:"Linux utility for synchronizing VirtualBox shared folders with a local workspace.",summary:"A Linux classroom utility that keeps VirtualBox shared-folder content synchronized with a local working directory.",status:"Stable",runtime:"tool",tags:[{name:"Shell",kind:"language"},{name:"Linux",kind:"platform"},{name:"VirtualBox",kind:"tool"}],highlights:["CLI and GUI entry points","systemd service integration","Shared-folder synchronization"]},
{slug:"setda-dev",name:"SETDA1494 Developer Hub",category:"Web",description:"Developer portfolio, release archive and web-game platform.",summary:"This site: a project archive, release surface, account system and browser-game host.",status:"Phase 3",featured:true,runtime:"web",tags:[{name:"TypeScript",kind:"language"},{name:"Next.js",kind:"tool"},{name:"PostgreSQL",kind:"tool"}],highlights:["Project detail routes","DB-backed accounts and sessions","Cloud-save API foundation"],webGame:{enabled:false}}
];
export const categories=["Game","Web","Software","OS / System","Server / Infra","Hardware / 3D Printing"];
export const activities=["Developer Hub Phase 3 project detail routes added","Browser launch policy restricted to registered web games","Account and cloud-save foundation integrated","Project2080 and REMOTE_HOME indexed"];
export const stack=["TypeScript","C#","C","Python","Next.js","Unity","Linux","Docker","Git","VS Code"];
export function getProject(slug:string){return projects.find(p=>p.slug===slug)}
export function playableWebGames(){return projects.filter(p=>p.runtime==="web"&&p.webGame?.enabled&&p.webGame.entry)}
